### ISSUE TITLE
File Storage in Django

### ISSUE THREAD

**Issue by Rup-Narayan-Rajbanshi** [toggle-corp/togglecorp-backend#7]
Doc : https://notes.tools.togglecorp.com/Fc_CVMoFRaWbcj75bfCIxQ

**Comment by sudan45** [comment]
Move to Wikijs

**Comment by Rup-Narayan-Rajbanshi** [comment]
wikijs : https://wikijs.local.togglecorp.com/en/dev-catchup/backend/custom_file_path_django
